### ISSUE TITLE
敢有法度用GitHub 配合家己的lfs server

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/pian7sik4#2]
只是問問咧，因為你攏做好git server矣

按呢就免設定https抑是git server

**Comment by leo424y** [comment]
測試OK！
可用github host repo (public/private) + 自家 lfs

進行 https clone / push 

用github 有gui好管理repo

就看 @sih4sing5hong5  決定要host在哪囉

**Comment by sih4sing5hong5** [comment]
github可能會較好？
我只是誠歹勢一直改來改去 XD

**Comment by leo424y** [comment]
這樣才好！我有練到架git server! 超感謝

那麼語料git 就host在github，只需要改repo remove url 與 lfsconfig

那我開一個聲學語料repo (private)

https://github.com/twgo/siann1-hak8_boo5-hing5-wav

後面有新的語料也可這樣開囉

**Comment by sih4sing5hong5** [comment]
若按呢，repo名直接叫`辨識語料`， `pian7sik4_gi2liau7`

dockerfile你直接改，看ok無

**Comment by leo424y** [comment]
名字改好了，dockerfile換路徑也OK，但發現repo要public比較好處理。

問題在於，private要clone的話需要 username password 

我把它public後，不用填就能clone
一定要private的話
要有個公用的帳號？
或者就public，不在iis內還是抓不到檔案

**Comment by sih4sing5hong5** [comment]
private 會當看有ssh_token通用無
若傷複雜，用public應該嘛是會用著

lfs本身是按怎認證？

**Comment by leo424y** [comment]
之前就是要讓docker方便clone才用http/https的，
ssh還要處理key的問題，
若可以，建議用public
未來若還有合作伙伴的話或許較便於溝通

lfs認證寫在 repo 的 lfsconfig 
因為在內網，目前走 http

**Comment by sih4sing5hong5** [comment]
github做public應該是無問題

毋過lfs除了外網以外
內網的電腦攏有法度攻擊？

**Comment by leo424y** [comment]
只怕內網攻擊，我這就趕快來看lfs 的 https 設定

**Comment by leo424y** [comment]
git-lfs 只提供 http, https 連線
又https所需之ssl証需費用

將lfsconfig刪掉可保lfs安全性

又，如聲學docker為public，要取語料時再加回去又需公開，仍會有安全問題

是否待iis內網有資安問題後再對此加強？

不知 @sih4sing5hong5  對此有何看法

參見 
https://github.com/git-lfs/git-lfs/wiki/Tutorial
http://publicca.hinet.net/SSL-03.htm
http://www.sonatype.org/nexus/2017/01/31/running-the-nexus-3-docker-container-with-ssl/
https://github.com/SergK/nexus3-ssl
https://github.com/TerrenceMiao/nexus/wiki/Setup-HTTPS-access-in-Nexus-Repository-Manager-OSS-3.0.0

**Comment by leo424y** [comment]
目前已降低lfs遭內網攻擊安全性問題

我使用 Nexus Repository Manager 之 Roles Privileges 功能

令 anonymous user權限只有read
故 未來docker要存取語料只需 anonymous
https://github.com/twgo/pian7sik4_gi2liau7/blob/master/.lfsconfig
要lfs push時，可再手動將username/password加進去
<img width="855" alt="screen shot 2018-02-27 at 3 01 50 pm" src="https://user-images.githubusercontent.com/1384394/36715130-d668b41e-1bcf-11e8-8806-9a50a4d3c02d.png">

**Comment by sih4sing5hong5** [comment]
抑是read嘛愛password
然後password用copy入去docker內底，按呢敢有較好？

**Comment by leo424y** [comment]
已改成clone要name/password，git(免pwd) / lfs(需要pwd) 是分開的

所以要在 git lfs clone 前塞pwd給語料的 git repo 的 .lfsconfig

我再來研究一下docker copy能不能辦到

**Comment by leo424y** [comment]
self host lfs server ok
